/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as manualTokenSol from "./ManualToken.sol";
export type { manualTokenSol };
export type { OurToken } from "./OurToken";
