/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TokenERC20__factory } from "./TokenERC20__factory";
export { TokenRecipient__factory } from "./TokenRecipient__factory";
