/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as manualTokenSol from "./ManualToken.sol";
export { OurToken__factory } from "./OurToken__factory";
